name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add upstream https://github.com/pigzillaaaaa/daddylive.git
          git fetch upstream

      - name: Remove all files except workflows
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.github' -exec rm -rf {} +

      - name: Copy all files from upstream except workflows
        run: |
          git checkout upstream/main -- .
          rm -f .github/workflows/*.yml

      - name: Restore your workflows
        run: |
          git checkout HEAD -- .github/workflows

      - name: Commit and force push
        run: |
          git add .
          git commit -m "Force sync from upstream except workflows" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin main --force
