- name: Show root files before deletion
  run: ls -la

- name: Remove everything except workflows
  run: |
    find . -mindepth 1 -maxdepth 1 ! -name '.github' -exec rm -rf {} +

- name: Show root files after deletion
  run: ls -la

- name: Fetch upstream main branch
  run: git fetch upstream main

- name: Checkout upstream files
  run: git checkout upstream/main -- .

- name: Restore workflows folder
  run: git checkout HEAD -- .github/workflows

- name: Show root files after checkout
  run: ls -la

- name: Commit and push changes
  run: |
    git config user.name "GitHub Action"
    git config user.email "action@github.com"
    git add .
    git commit -m "Sync from upstream except workflows" || echo "No changes to commit"
    git push origin main
