name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # We'll handle auth manually

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/pigzillaaaaa/daddylive.git

      - name: Fetch upstream
        run: git fetch upstream main

      - name: Backup workflows
        run: |
          mkdir -p .github/tmp-workflows
          cp -r .github/workflows/* .github/tmp-workflows/ || echo "No workflows to back up"

      - name: Reset to upstream
        run: |
          # Clean and reset to upstream
          git reset --hard upstream/main
          git clean -fdx
          echo "Reset complete"

      - name: Restore workflows
        run: |
          mkdir -p .github/workflows
          cp -r .github/tmp-workflows/* .github/workflows/ || echo "No workflows to restore"

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Sync with upstream except workflows"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
            git push origin main
          else
            echo "No changes to commit"
