name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          echo "Setting up Git identity..."
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add upstream remote
        run: |
          echo "Adding upstream remote..."
          git remote add upstream https://github.com/pigzillaaaaa/daddylive.git
          echo "✓ Upstream remote added"

      - name: Fetch upstream main
        run: |
          echo "Fetching upstream main branch..."
          git fetch upstream main
          echo "✓ Upstream main fetched"

      - name: Backup workflows
        run: |
          echo "Backing up existing workflows..."
          mkdir -p .github/tmp-workflows
          cp -r .github/workflows/* .github/tmp-workflows/ || echo "No workflows to back up"
          echo "✓ Workflows backed up"

      - name: Hard reset to upstream
        run: |
          echo "Resetting repo to upstream/main..."
          git reset --hard upstream/main
          git clean -fdx
          echo "✓ Repo reset to upstream"

      - name: Restore workflows
        run: |
          echo "Restoring workflows..."
          mkdir -p .github/workflows
          cp -r .github/tmp-workflows/* .github/workflows/ || echo "No workflows to restore"
          echo "✓ Workflows restored"

      - name: Commit and push changes
        run: |
          echo "Committing and pushing changes..."
          git add .
          git commit -m "Sync from upstream with workflows preserved" || echo "No changes to commit"
          git push origin main
          echo "✓ Sync complete"
