name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo (without credentials)
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # We'll handle pushing manually

      - name: Add upstream remote
        run: git remote add upstream https://github.com/pigzillaaaaa/daddylive.git

      - name: Fetch upstream main branch
        run: git fetch upstream main

      - name: Replace repo content except workflows
        run: |
          # Delete all files and folders except the .github folder
          find . -mindepth 1 -maxdepth 1 ! -name '.github' -exec rm -rf {} +

          # Checkout all files from upstream main branch (overwrites current files except .github)
          git checkout upstream/main -- .

          # Restore only your workflow folder from your current branch (HEAD)
          git checkout HEAD -- .github/workflows

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Sync with upstream except workflows"
          git push origin main
