name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Required for custom push setup

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Ensure we're on main branch
        run: |
          echo "Switching to main branch..."
          git checkout main

      - name: Add upstream safely
        run: |
          git remote remove upstream 2>/dev/null || true
          git remote add upstream https://github.com/pigzillaaaaa/daddylive.git
          echo "✓ Upstream remote added"

      - name: Fetch upstream
        run: |
          git fetch upstream main
          echo "✓ Fetched upstream"

      - name: Backup workflows
        run: |
          echo "Backing up workflows..."
          mkdir -p .github/tmp-workflows
          cp -r .github/workflows/* .github/tmp-workflows/ || echo "No workflows to back up"

      - name: Reset to upstream
        run: |
          git reset --hard upstream/main
          git clean -fdx
          echo "✓ Repo reset to match upstream/main"

      - name: Restore workflows
        run: |
          mkdir -p .github/workflows
          cp -r .github/tmp-workflows/* .github/workflows/ || echo "No workflows to restore"
          echo "✓ Workflows restored"

      - name: Push changes back to your fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git add .
          git commit -m "Sync with upstream (preserving workflows)" || echo "No changes to commit"
          git push origin main --force
